#!/bin/bash
#
# init script to start the cron daemon
#
# Written by github/sseiber

source /etc/init.d/functions

RETVAL=0
prog="crond"
desc="cron daemon"

start() {
	echo -n $"Starting $desc ($prog): "
	/sbin/crond

	if [ $RETVAL -eq 0 ]; then
		success "$prog startup"
	else
		failure "$prog startup"
	fi
	echo
}

stop() {
	echo -n $"Stopping $desc ($prog): "

	pkill -f crond

	if [ $RETVAL -eq 0 ]; then
		success "$prog shutdown"
	else
		failure "$prog shutdown"
	fi
	echo
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo $"Usage $0 {start|stop|restart}"
	RETVAL=1
esac

exit $RETVAL